# Generated by Django 3.0.6 on 2020-05-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewalls',
            name='ipadd',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='loadbalancers',
            name='ipadd',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='routers',
            name='ipadd',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='switches',
            name='ipadd',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
