# Generated by Django 3.0.6 on 2020-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20200521_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalls',
            name='datacenter',
            field=models.CharField(choices=[('JC', 'Johns Creek'), ('LW', 'Lewisville'), ('PHX', 'Phoenix')], default='LW', max_length=30),
        ),
        migrations.AlterField(
            model_name='loadbalancers',
            name='datacenter',
            field=models.CharField(choices=[('JC', 'Johns Creek'), ('LW', 'Lewisville'), ('PHX', 'Phoenix')], default='LW', max_length=30),
        ),
        migrations.AlterField(
            model_name='routers',
            name='datacenter',
            field=models.CharField(choices=[('JC', 'Johns Creek'), ('LW', 'Lewisville'), ('PHX', 'Phoenix')], default='LW', max_length=30),
        ),
        migrations.AlterField(
            model_name='switches',
            name='datacenter',
            field=models.CharField(choices=[('JC', 'Johns Creek'), ('LW', 'Lewisville'), ('PHX', 'Phoenix')], default='LW', max_length=30),
        ),
    ]
